### ISSUE TITLE
Error: Validation Failed

### ISSUE THREAD

**Issue by arcuri82** [ScaCap/action-surefire-report#161] opened 2023-05-23 11:16 UTC
Hi,
 trying to use this action. Added it with:

```
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
```

however, no test report is created. I get the following in the logs of the action:

```
Result: 4522 tests run, 28 skipped, 6 failed.
Posting status 'completed' with conclusion 'failure' to refs/heads/minimize (sha: d343f8acf441370d10b7c74c4bad42f46c2fd404)
Error: Validation Failed: {"resource":"CheckRun","code":"invalid","field":"annotations"}
```

currently running on a branch. Am I doing something wrong? or is it a bug?

**Comment by ghaiszaher** [comment] 2023-06-02 12:35
@arcuri82 is this easily reproducible on some public repository? I can only imagine that permissions are missing:
```yaml
    permissions:
      checks: write
      contents: read
    steps:
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
```

Also see https://github.com/ScaCap/action-surefire-report#example-usage

**Comment by arcuri82** [comment] 2023-06-02 13:17
thanks for the reply. However, since I reported this issue I have been trying other alternatives as well, and in the end the following worked for me:

```
      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
```

the repository I am using is [EvoMaster](https://github.com/EMResearch/EvoMaster), which is public

**Comment by ghaiszaher** [comment] 2023-06-02 21:42
I was able to reproduce a similar case because the annotation `message` was empty. Attempt to fix: https://github.com/ScaCap/action-surefire-report/pull/164

If you face the same issue again, please rerun the job with debug enabled to get more insights.

**Comment by ghaiszaher** [comment] 2023-07-18 16:07
I will close this issue as fixed with https://github.com/ScaCap/action-surefire-report/pull/164, feel free to reopen if you still face it with the latest version.

**Closed by ghaiszaher** 2023-07-18 16:08 UTC
